import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import"../font/FiraCode-VariableFont_wght.ttf"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='font-FiraCode'>{children}</body>
    </html>
  );
}
